### ISSUE TITLE
DownloadAdd icon suggestion

### ISSUE THREAD

**Issue by jEsuSdA** [PapirusDevelopmentTeam/papirus-filezilla-themes#1]
If UploadAdd is this:
![uploadadd](https://cloud.githubusercontent.com/assets/5833446/20541333/09b02e9a-b0fd-11e6-96a3-8dee8f3e7bcd.png)

DownloaAdd must be this:
![downloadadd](https://cloud.githubusercontent.com/assets/5833446/20541329/040912f4-b0fd-11e6-9556-a113814c5666.png)

What do you think?

**Comment by varlesh** [comment]
Yes, its better. Soon fixed

**Comment by varlesh** [comment]
done
