### ISSUE TITLE
Issue Installing On Mac

### ISSUE THREAD

**Issue by wkdcode-josh** [PapirusDevelopmentTeam/papirus-filezilla-themes#11]
When I run the following command:
sudo make install

I receive the following and am unable to install:

mkdir -p /usr/share/filezilla/resources
mkdir: /usr/share/filezilla/resources: Operation not permitted

**Comment by SmartFinn** [comment]
The Makefile doesn't support OS X. We don't use Mac, so can't help you with the installation. If you find a way to install FileZilla themes on Mac please post instruction here #9.
