### ISSUE TITLE
Dark Theme Does Not theme Filezilla in Win 10... Need Help

### ISSUE THREAD

**Issue by koolx** [PapirusDevelopmentTeam/papirus-filezilla-themes#12]
I have win 10. I installed your dark theme for filezilla: 'papirus-filezilla-themes-master'. But nothing gets dark. Its still white. What do I do?

**Comment by SmartFinn** [comment]
That is an icon theme, not a skin (which FileZilla is not supported). Change window color to dark in your system.

**Comment by koolx** [comment]
But my win 10 is dark mode like windows explorer. Filezilla still is white. I dont get it.

**Comment by SmartFinn** [comment]
Seems Fillezilla on Windows does not support any skins.

**Comment by koolx** [comment]
I really dont know. I downloaded filezilla yesterday. My 1st time playing it.

**Comment by vincent1890** [comment]
UP not work windows dark mode but filezilla white

**Comment by allsite** [comment]
It's sad dark mode doesn't work in FZ. And when I say "dark mode", I mean black as the night, not some mid-tone gray blunder.

**Comment by Robby9705** [comment]
So Can You Tell Us What The Background Name Is And Where You Got It From?

**Comment by tauseedzaman** [comment]
is there any proper way to to enable dark mode on filezilla?

**Comment by geedogz** [comment]
Dont bother. The dev doesnt care and is late when every app has dark mode. Just use qbitorrent. It has dark mode the dev cares about for its users to have

**Comment by allsite** [comment]
> is there any proper way to to enable dark mode on filezilla?

Unfortunately not. For those of us grinding the midnight oil FZ will continue to be a blinding burst of light.

Isn't it an odd default, pixels at max brightness vs completely off, not using any battery or wear on the screen. Mostly the older crowd thinksdark theme is for kids because they simply don't understand the reality that not everyone works in a cubicle under fluorescent lighting.

**Comment by geedogz** [comment]
> Mostly the older crowd thinksdark theme is for kids because they simply don't understand the reality that not everyone works in a cubicle under fluorescent lighting.

The only older crowd here is YOU.  Youre living in 2009

**Comment by allsite** [comment]
> Dont bother. The dev doesnt care and is late when every app has dark mode. Just use qbitorrent. It has dark mode the dev cares about for its users to have

Am I missing something here? qbittorent has FTP functionality? Please enlighten me.

**Comment by geedogz** [comment]
> Am I missing something here? qbittorent has FTP functionality? Please enlighten me.

Youre missing DARK MODE

**Comment by allsite** [comment]
> > Am I missing something here? qbittorent has FTP functionality? Please enlighten me.
> 
> 
> 
> Youre missing DARK MODE

I'm not the developer of Filezilla and am here pushing for dark mode to be added. So I'm not sure what you're trying to say. Same team? 😁

**Comment by geedogz** [comment]
Go quibble with yourself. I'm outta here

**Comment by Kayzo** [comment]
Cant turn my filezilla into dark mode !!! any help plz ?
Cant understand how an app like filezilla mostly used everywhere does not have or support dark theme !!! do they even care ?!!

**Comment by geedogz** [comment]
I suggest other torrent managers since filezilla is dead. I've requested dark mode for years but the dev doesnt get it. I uninstalled filezilla

**Comment by PwrSrg** [comment]
Like @geedogz said, Firezilla is **DEAD**.  What you want is **[WinSCP](https://winscp.net)**

[WinSCP :: Official Site :: Free SFTP and FTP client for Windows](https://winscp.net/eng/index.php)

![WinSCP Dark](https://user-images.githubusercontent.com/711603/204037849-8b8618f7-79c3-401d-ab8b-0d63127cc6dd.png)

**Comment by Nodws** [comment]
yes just switch to a modern client. FZ devs are in their 60s enjoying retirement and lighting their homes with their gui

**Comment by Bleauhaus** [comment]
> yes just switch to a modern client. FZ devs are in their 60s enjoying retirement and lighting their homes with their gui

what a waste of a 'brand'

**Comment by Melivo** [comment]
> Dont bother. The dev doesnt care and is late when every app has dark mode. Just use qbitorrent. It has dark mode the dev cares about for its users to have

qbitorrent? what the hell??? That's P2P not FTP 🤦‍♂️

**Comment by Nikoichu** [comment]
Hey, since this thread is such a dumpster fire, I thought I'd enlighten (endarken?) the poor people stumbling on it in the future.
Basically, you need a PROPER dark theme for windows, not the excuse they provide by default in the "personalize" settings, because that doesn't affect 3rd party programs like FileZilla. For that you need UltraUX Theme Patcher or similar, and 3rd party themes.

Read how to do that here: https://www.deviantart.com/niivu/art/Installing-Windows-Themes-UPDATED-708835586

**Comment by Melivo** [comment]
> Hey, since this thread is such a dumpster fire, I thought I'd enlighten (endarken?) the poor people stumbling on it in the future. Basically, you need a PROPER dark theme for windows, not the excuse they provide by default in the "personalize" settings, because that doesn't affect 3rd party programs like FileZilla. For that you need UltraUX Theme Patcher or similar, and 3rd party themes.
> 
> Read how to do that here: https://www.deviantart.com/niivu/art/Installing-Windows-Themes-UPDATED-708835586

Why should anyone do that? A lot of other programs have a "use system settings" option and automatically switch to dark mode because they can detect when you're using dark mode on windows.

Simply switch to WinSCP and forget FileZilla. Thats it. Win.

**Comment by crogonint** [comment]
I just want to mention that I think BloodRaven0 is right. If you want to make a trainwreck out of your Windows Color theme, go in to the Personalization / Colors / Contrast Theme and change to one of those Dark Mode themes. It will work. It will turn FillaZilla and other software dark. However, it mucks up the rest of the windows theme, and turns your desktop in to something resembling Windows 95.

You can manually change the settings in regedit if you want to spend a few hours manually editing the colors. However, I think that the third party suggestion above is the way to go, so I'm off to look in to that now.

**Comment by proglyk** [comment]
We are need background, not icons. Just use WinSCP instead, guys
