### ISSUE TITLE
48x48 icons for windows

### ISSUE THREAD

**Issue by typhoon71** [PapirusDevelopmentTeam/papirus-filezilla-themes#13]
First thing first, thanks for this awesome theme.

Now the question: would it be possible to provide a 48x48 iconset too? On my windows7, if I set it to use the 32x32 it actually shows them scaled to 48x48... which is horrible. 

I have no issue on the linux machine, just on windows. Thanks.

**Comment by SmartFinn** [comment]
Added in [20200105](https://github.com/PapirusDevelopmentTeam/papirus-filezilla-themes/releases/tag/20200105)

**Comment by typhoon71** [comment]
Thanks!
