### ISSUE TITLE
Any chance to see that on PC ?

### ISSUE THREAD

**Issue by PABfr** [PapirusDevelopmentTeam/papirus-filezilla-themes#18]
Nice theme : anyway to make it works for PC ?

**Comment by SmartFinn** [comment]
Do you mean on Windows? See [Install on Windows](https://github.com/PapirusDevelopmentTeam/papirus-filezilla-themes#windows).

**Comment by PABfr** [comment]
Thanks for the quick reply. I've already tried : 
_1. Download the zip archive attached to the latest release.
2. Unzip the folders to <installition_path>\resources (usually C:\Program Files\FileZilla FTP Client\resources)._

It works well for changing the icons, not for the background & windows UI... 
I'm looking for a dark mode.
I've read elsewhere you have to change windows theme to high contrast, which changes all apps... not the solution I'm looking for. :/

**Comment by SmartFinn** [comment]
See pined issue https://github.com/PapirusDevelopmentTeam/papirus-filezilla-themes/issues/12 TLDR: no change do it on Windows. The background is not a part of the icon theme.
