### ISSUE TITLE
[Windows 11] Papirus Dark only changes icon color, not background color

### ISSUE THREAD

**Issue by dredshep** [PapirusDevelopmentTeam/papirus-filezilla-themes#20]
![image](https://user-images.githubusercontent.com/78047001/152370858-4d66a2e0-2264-418e-995c-825017296dcd.png)

I unzipped the latest release into resources, picked Papirus Dark and this is what I see. I'm not sure if this is a problem with Win11, or with Papirus, or with what I did.

![image](https://user-images.githubusercontent.com/78047001/152371067-1af80a10-a483-4f8a-b66a-e1fb19870c92.png)

All other programs are in dark mode:

![image](https://user-images.githubusercontent.com/78047001/152371557-834ea73a-c2c9-44e2-8436-b4bf9d9e0662.png)

**Comment by SmartFinn** [comment]
See pinned issue #12
