### ISSUE TITLE
Theme needs to be updated for latest FileZilla

### ISSUE THREAD

**Issue by gregorydk** [PapirusDevelopmentTeam/papirus-filezilla-themes#4]
Since FileZilla 3.23 the icon themes have changed and Papirus needs to be updated.

> Improvements to the sizing of icons and other user interface elements on high-DPI displays. For technical reasons, existing theme settings have been reverted to their default values. They can be changed again in the settings dialog.

https://filezilla-project.org/versions.php?version=3.24.0&oldversion=3.21.0

Fix:
Use 64 pixel (or higher) icons and change theme.xml

**Comment by varlesh** [comment]
I'm convert 16 to 32 and 64px's... please check

**Comment by SmartFinn** [comment]
@varlesh I think need one set with 480x480 size. Look inside resources/default directory https://sourceforge.net/projects/filezilla/files/FileZilla_Client/3.24.0/FileZilla_3.24.0_x86_64-linux-gnu.tar.bz2/download

**Comment by varlesh** [comment]
No, 480x480 blurred icon for little sizes... and i think no body use 480px icons on toolbar... because it's 10K or more...
Filezilla have scale (for change icon size) - that's all. Now available 3 sizes 16px, 32px and 64px

**Comment by varlesh** [comment]
See 64px, i think this enough for HiDPi:
![image](https://cloud.githubusercontent.com/assets/8083855/22123428/fcc0ba4e-dea4-11e6-82d2-14a06f796494.png)

**Comment by SmartFinn** [comment]
@varlesh latest version with default theme

![screenshot from 2017-01-19 22-14-37](https://cloud.githubusercontent.com/assets/819186/22123568/cc5e6000-de94-11e6-8c38-d023e8728d5b.png)

Not blurred.

**Comment by varlesh** [comment]
@SmartFinn ты выставил 1,50 в scale а у меня четные значения... Не вижу смысла в 480

**Comment by SmartFinn** [comment]
@varlesh в новой версии нет выбора размеров, и если захочешь немного увеличить - получишь мыло. Нужно на ощупь угадывать где нужные размеры

![screenshot from 2017-01-19 22-25-07](https://cloud.githubusercontent.com/assets/819186/22123913/5a112a62-de96-11e6-8161-b13588d9e864.png)

**Comment by varlesh** [comment]
@SmartFinn я на новой версии и тестировал, там scale доступен, у меня 3 размера 16, 32 и 64.
Scale не для мыла 1.0, 2.0 и 4.0 - вполне достаточна для всех видов дисплеев.
Почему оно не отображается в превью, вот это я хз...

**Comment by varlesh** [comment]
вроде пофиксил превью

**Comment by SmartFinn** [comment]
@varlesh ок, я попробую сделать 480 и посмотреть как оно на старых работает. На новой как видишь проблем с блюром и переходными размерами нет.

**Comment by varlesh** [comment]
480 это значок увеличенный в 10раз от 48px<24px
у меня же другой совсем размер 64px<32px<16px
Нужно портировать под 24px...

**Comment by varlesh** [comment]
Там кстати есть и другие темы, типа tango, sun и т.д. Вот тоже самое, как у меня

**Comment by varlesh** [comment]
@gregorydk You have HiDPi-display, can test new icons?

**Comment by SmartFinn** [comment]
@varlesh это понятно, их еще не портировали под новую версию. Остается только вопрос как оно в станой будет работать.

У меня кстати превью по прежнему сломаны.

**Comment by varlesh** [comment]
> У меня кстати превью по прежнему сломаны.

Странно, у меня пашут:
![image](https://cloud.githubusercontent.com/assets/8083855/22124721/69aaea62-deaa-11e6-9baa-0ad4cd29d8b4.png)

**Comment by SmartFinn** [comment]
@varlesh уже заработали, не знаю что повлияло...

**Comment by varlesh** [comment]
Anyone have 4K-display? :) please test

**Comment by SmartFinn** [comment]
@varlesh с 480x480
![screenshot from 2017-01-19 23-13-45](https://cloud.githubusercontent.com/assets/819186/22125598/02713034-de9d-11e6-80b7-a304e03597c5.png)

Со scale=1 мутно, все что выше терпимо. Старые версии это не поддерживают, так что смысла заморачиваться нет.

**Comment by varlesh** [comment]
Всмысле терпимо? Есть вариант с четкими значками, без размытий?

**Comment by SmartFinn** [comment]
@varlesh последний скриншот открой, тебе как? Мне вроде ничего, я бы пользоватся. Лучше чем предыдущий с тем же scale.

**Comment by varlesh** [comment]
последний скриншот - мыло

**Comment by varlesh** [comment]
значки upload смотри

**Comment by SmartFinn** [comment]
@varlesh добавление 480x480 к имеющимся тоже бессмысленно, переходы в масштабировании это не сглаживает. Оставляй как есть.

Боюсь только что FileZilla недостаточно умная чтобы на HiDPi взять иконку 32x32 вместо 16x16 при scale factor 1.

**Comment by varlesh** [comment]
Ну scale же есть, накрутят как надо... Я вообще на их месте лучше бы поддержку svg добавил

**Comment by gregorydk** [comment]
Icons look fine now. Unless you go scale=4, then they're a little blurry.
