### ISSUE TITLE
How to change to dark theme

### ISSUE THREAD

**Issue by jazithedev** [PapirusDevelopmentTeam/papirus-filezilla-themes#5]
How to change the whole FileZilla to dark theme and not only icons? I changed theme for Papirus and I still have very bright, white application..

**Comment by SmartFinn** [comment]
You should change the GTK theme to dark. For example, you can install [arc-theme](https://github.com/horst3180/arc-theme#packages) and choose Arc Dark, as in the screenshot.

**Comment by jazithedev** [comment]
Yup! This is it. Thanks!

**Comment by ernestp** [comment]
@ktrzos Is it possible to install GTK dark theme on macOS?

**Comment by varlesh** [comment]
@ktrzos It's not GTK theme, it's only icons. We not use Mac and don't know where located 3-d party icon themes for Filezilla. Maybe on `~/Applications/FileZilla.app/Contents/SharedSupport/resources/`

**Comment by hugoheml** [comment]
When I change the theme, only icons change but I don't have the dark theme why ?

**Comment by SmartFinn** [comment]
@hugolompto because it's an icon theme. FileZilla doesn't support skins.
