### ISSUE TITLE
is there any way to use it in windows 10

### ISSUE THREAD

**Issue by saostad** [PapirusDevelopmentTeam/papirus-filezilla-themes#6]
I like your theme, is there any way to use it in windows 10 ?

**Comment by SmartFinn** [comment]
I'm not a Windows user, so if someone knows, please tell us.

**Comment by varlesh** [comment]
@saostad Use Linux :laughing:

**Comment by pboesch** [comment]
Hi, the windows path is `C:\Program Files\FileZilla FTP Client\resources` but apparently you can not change window color, just icons.

**Comment by GabrielAPass** [comment]
Thanks for that info @pboesch .  It would be really great if anyone had the interest to figure out how to get this to work in Windows.  I also prefer Linux but many of us don't have the luxury of working in our ideal environment at work.  Right now, I am working on Win10 with a number of comfortably dark themed IDE's but still squinting at one glaring white FileZilla window.

**Comment by saostad** [comment]
> Thanks for that info @pboesch . It would be really great if anyone had the interest to figure out how to get this to work in Windows. I also prefer Linux but many of us don't have the luxury of working in our ideal environment at work. Right now, I am working on Win10 with a number of comfortably dark themed IDE's but still squinting at one glaring white FileZilla window.

I am using WinSCP, it has all the missing features of FileZilla plus more!

**Comment by karanikn** [comment]
Are the icons in format ico?
