### ISSUE TITLE
openSUSE package

### ISSUE THREAD

**Issue by GriefNorth** [PapirusDevelopmentTeam/papirus-filezilla-themes#7]
Hello, this is link for openSUSE(Leap 42.2, 42.3 and Tumbleweed) package http://software.opensuse.org//download.html?project=home%3AGNorth%3AArc_and_Papirus&package=papirus-filezilla-theme
My name is Alexander Postol and my OBS link https://build.opensuse.org/package/show/home:GNorth:Arc_and_Papirus/papirus-filezilla-theme

**Comment by SmartFinn** [comment]
@GriefNorth Hello,

Thanks for the package. I'll add it ASAP.

**Comment by GriefNorth** [comment]
Ok, thx so much
